name: Update publications

on:
  schedule:
    - cron: "0 5 1 * *" # 05:00 UTC on first of each month
  workflow_dispatch:

jobs:
  query:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout main branch
          uses: actions/checkout@v4 

        - name: Setup uv
          uses: astral-sh/setup-uv@v4
          with:
            enable-cache: true

        - name: Query pubmed
          run: |
            pushd backend > /dev/null
            uv run --frozen src/get_publications/run.py \
              ../frontend/data/publications.json
        
        # Only runs if there is a commit
        - name: Create PR 
          uses: peter-evans/create-pull-request@v7
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            commit-message: "[BOT] Update publications"
            title: "[BOT] Update publications"
            body: New publications found - check before merging
            branch: bot/update_publications